---
title: "p8105_mtp_zz3168"
author: "Zixuan Zhang"
date: "2023-10-20"
output: github_document
---

```{r}
library(readr)
library(readxl)
library(tidyverse)
library(dplyr)
```

## Problem 1 
##Data import, cleaning, and quality control
```{r}
coa_data_1 = read_xlsx("data/USPS CHANGE OF ADDRESS NYC.xlsx", sheet = c("2018")) 
  coa_data_2 = read_xlsx("data/USPS CHANGE OF ADDRESS NYC.xlsx", sheet = c("2019")) 
coa_data_3 = read_xlsx("data/USPS CHANGE OF ADDRESS NYC.xlsx", sheet = c("2020")) 
coa_data_4 = read_xlsx("data/USPS CHANGE OF ADDRESS NYC.xlsx", sheet = c("2021")) 
coa_data_5 = read_xlsx("data/USPS CHANGE OF ADDRESS NYC.xlsx", sheet = c("2022"))

coa_data = 
  bind_rows(coa_data_1,coa_data_2,coa_data_3,coa_data_4,coa_data_5) |> 
  janitor::clean_names() |> 
  separate(month, into = c("year", "month", "date") ) |> 
  mutate(net_change = total_perm_in - total_perm_out) |> 
  rename(zip_code = zipcode) 
 



zip_data = read_csv("data/Zip Codes.csv") |> 
  janitor::clean_names() |> 
  rename(borough_variable = county_name )


  
combine_data = 
  left_join(zip_data, coa_data,by="zip_code")
  
  

```

##describe Tidy Dataset

```{r}
unique_zips =
  combine_data |> 
  select(zip_code) |> 
  distinct()

unique_neighborhoods =
  combine_data |> 
  drop_na() |> 
  select(neighborhood) |> 
  distinct() 
  

```

##Compare city
```{r}
Manhattan_co =
  combine_data |> 
  filter(borough_variable == "Manhattan") |> 
  count(city) |> 
  arrange(desc(n)) |> 
  mutate(rank = row_number()) 


queens_co =
  combine_data |> 
  filter(borough_variable == "Queens") |> 
  count(city) |> 
  arrange(desc(n)) |> 
  mutate(rank = row_number()) 
  


```


## Problem 2
#EDA
```{r}
average_df = 
  combine_data |> 
  group_by(borough_variable, year) |> 
  summarize(average_df = mean(net_change, na.rm = TRUE)) |> 
  mutate(year = as.integer(year))

low_df = 
  combine_data |> 
  arrange(net_change) |> 
  select(zip_code, neighborhood, year, month, net_change) |> 
  head(n = 5)


high_2020 =
  combine_data |> 
  filter(year < 2020) |> 
  arrange(desc(net_change)) |> 
  select(zip_code, neighborhood, year, month, net_change) |> 
  head(n = 5)
  



```



## Visualization:
```{r}
combine_plot = 
  combine_data |> 
  mutate(month = as.integer(month),
         year = as.integer(year))
```

